// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateSynchronizationUpdate - An input object to updating a Synchronization
type CreateSynchronizationUpdate struct {
	Sync *CreateSynchronizationSyncUpdate `json:"sync,omitempty"`
}
