// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateSynchronizationInput - An input object to creating a Synchronization
type CreateSynchronizationInput struct {
	Sync *CreateSynchronizationSyncInput `json:"sync,omitempty"`
}
