// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Synchronization - A Synchonization object
type Synchronization struct {
	Sync *SyncronizationSyncOutput `json:"sync,omitempty"`
}
