// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Synchronization - An order helps you make coffee
type Synchronization struct {
	Sync *SyncronizationSyncOutput `json:"sync,omitempty"`
}
