// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"snowmirror/internal/sdk"
	"snowmirror/internal/sdk/pkg/models/shared"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ provider.Provider = &SnowmirrorProvider{}

type SnowmirrorProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// SnowmirrorProviderModel describes the provider data model.
type SnowmirrorProviderModel struct {
	ServerURL types.String `tfsdk:"server_url"`
	Password  types.String `tfsdk:"password"`
	Username  types.String `tfsdk:"username"`
}

func (p *SnowmirrorProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "snowmirror"
	resp.Version = p.version
}

func (p *SnowmirrorProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: `SnowMirror API: This document is a guide which will walk you through SnowMirror REST API. ` + "\n" +
			`The purpose of the REST API is to allow developers to integrate SnowMirror with other applications.`,
		Attributes: map[string]schema.Attribute{
			"server_url": schema.StringAttribute{
				MarkdownDescription: "Server URL (defaults to http://localhost:9090)",
				Optional:            true,
				Required:            false,
			},
			"password": schema.StringAttribute{
				Optional:  true,
				Sensitive: true,
			},
			"username": schema.StringAttribute{
				Optional:  true,
				Sensitive: true,
			},
		},
	}
}

func (p *SnowmirrorProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data SnowmirrorProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ServerURL := data.ServerURL.ValueString()

	if ServerURL == "" {
		ServerURL = "http://localhost:9090"
	}

	password := data.Password.ValueString()
	username := data.Username.ValueString()
	security := shared.Security{
		Password: password,
		Username: username,
	}

	opts := []sdk.SDKOption{
		sdk.WithServerURL(ServerURL),
		sdk.WithSecurity(security),
	}
	client := sdk.New(opts...)

	resp.DataSourceData = client
	resp.ResourceData = client
}

func (p *SnowmirrorProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewSynchronizationResource,
	}
}

func (p *SnowmirrorProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewSynchronizationDataSource,
	}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &SnowmirrorProvider{
			version: version,
		}
	}
}
