// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"snowmirror/internal/sdk"
	"snowmirror/internal/sdk/pkg/models/operations"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &SynchronizationDataSource{}
var _ datasource.DataSourceWithConfigure = &SynchronizationDataSource{}

func NewSynchronizationDataSource() datasource.DataSource {
	return &SynchronizationDataSource{}
}

// SynchronizationDataSource is the data source implementation.
type SynchronizationDataSource struct {
	client *sdk.Snowmirror
}

// SynchronizationDataSourceModel describes the data model.
type SynchronizationDataSourceModel struct {
	ID   types.Int64                     `tfsdk:"id"`
	Sync *CreateSynchronizationInputSync `tfsdk:"sync"`
}

// Metadata returns the data source type name.
func (r *SynchronizationDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_synchronization"
}

// Schema defines the schema for the data source.
func (r *SynchronizationDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Synchronization DataSource",

		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Required:    true,
				Description: `The ID of the order get.`,
			},
			"sync": schema.SingleNestedAttribute{
				Optional: true,
				Attributes: map[string]schema.Attribute{
					"active": schema.BoolAttribute{
						Optional: true,
					},
					"allow_inherited_columns": schema.BoolAttribute{
						Optional:    true,
						Description: `SnowMirror checks if columns exist in ServiceNow. If this flag is set to true,`,
					},
					"auto_schema_update": schema.BoolAttribute{
						Optional: true,
					},
					"columns": schema.ListNestedAttribute{
						Optional: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									Optional: true,
								},
							},
						},
					},
					"columns_to_exclude": schema.ListNestedAttribute{
						Optional: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									Optional: true,
								},
							},
						},
					},
					"delete_strategy": schema.StringAttribute{
						Optional: true,
					},
					"encoded_query": schema.StringAttribute{
						Optional: true,
					},
					"full_load_scheduler": schema.SingleNestedAttribute{
						Optional: true,
						Attributes: map[string]schema.Attribute{
							"begin_date": schema.StringAttribute{
								Optional: true,
							},
							"execution_type": schema.StringAttribute{
								Optional: true,
							},
							"type": schema.StringAttribute{
								Optional: true,
							},
						},
					},
					"mirror_table": schema.StringAttribute{
						Required:    true,
						Description: `Name of the table in mirror database where the data will be migrated.`,
					},
					"name": schema.StringAttribute{
						Required:    true,
						Description: `Display name of the synchronization.`,
					},
					"reference_field_type": schema.StringAttribute{
						Optional:    true,
						Description: `Defines how to synchronize reference field types.`,
					},
					"run_immediately": schema.BoolAttribute{
						Optional: true,
					},
					"scheduler": schema.SingleNestedAttribute{
						Optional: true,
						Attributes: map[string]schema.Attribute{
							"begin_date": schema.StringAttribute{
								Optional: true,
							},
							"type": schema.StringAttribute{
								Optional: true,
							},
						},
					},
					"scheduler_priority": schema.StringAttribute{
						Optional: true,
					},
					"table": schema.StringAttribute{
						Optional:    true,
						Description: `Name of the table in ServiceNow.`,
					},
					"view": schema.StringAttribute{
						Optional:    true,
						Description: `Name of the view in ServiceNow.`,
					},
				},
			},
		},
	}
}

func (r *SynchronizationDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Snowmirror)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.Snowmirror, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *SynchronizationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *SynchronizationDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	id := data.ID.ValueInt64()
	request := operations.GetSynchronizationRequest{
		ID: id,
	}
	res, err := r.client.Synchronization.GetSynchronization(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.Synchronization == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromGetResponse(res.Synchronization)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
