// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"snowmirror/internal/sdk/pkg/models/shared"
)

func (r *SynchronizationDataSourceModel) RefreshFromGetResponse(resp *shared.SyncronizationSyncOutput) {
	r.ID = types.Int64Value(resp.ID)
	r.Name = types.StringValue(resp.Name)
	if resp.Table != nil {
		r.Table = types.StringValue(*resp.Table)
	} else {
		r.Table = types.StringNull()
	}
}
