// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type SyncronizationSyncOutputScheduler struct {
	BeginDate            types.String   `tfsdk:"begin_date"`
	Days                 []types.String `tfsdk:"days"`
	IncLoadExecutionType types.String   `tfsdk:"inc_load_execution_type"`
	Time                 types.String   `tfsdk:"time"`
	Type                 types.String   `tfsdk:"type"`
	Visible              types.Bool     `tfsdk:"visible"`
}
