// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type CreateSynchronizationSyncInputScheduler struct {
	BeginDate types.String `tfsdk:"begin_date"`
	Type      types.String `tfsdk:"type"`
}
