// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type CreateSynchronizationInputSync struct {
	Active                types.Bool                                       `tfsdk:"active"`
	AllowInheritedColumns types.Bool                                       `tfsdk:"allow_inherited_columns"`
	AutoSchemaUpdate      types.Bool                                       `tfsdk:"auto_schema_update"`
	Columns               []CreateSynchronizationInputSyncColumns          `tfsdk:"columns"`
	ColumnsToExclude      []CreateSynchronizationInputSyncColumns          `tfsdk:"columns_to_exclude"`
	DeleteStrategy        types.String                                     `tfsdk:"delete_strategy"`
	EncodedQuery          types.String                                     `tfsdk:"encoded_query"`
	FullLoadScheduler     *CreateSynchronizationInputSyncFullLoadScheduler `tfsdk:"full_load_scheduler"`
	ID                    types.Int64                                      `tfsdk:"id"`
	MirrorTable           types.String                                     `tfsdk:"mirror_table"`
	Name                  types.String                                     `tfsdk:"name"`
	ReferenceFieldType    types.String                                     `tfsdk:"reference_field_type"`
	RunImmediately        types.Bool                                       `tfsdk:"run_immediately"`
	Scheduler             *CreateSynchronizationInputSyncScheduler         `tfsdk:"scheduler"`
	SchedulerPriority     types.String                                     `tfsdk:"scheduler_priority"`
	Table                 types.String                                     `tfsdk:"table"`
	View                  types.String                                     `tfsdk:"view"`
}
