// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteSynchronizationRequest struct {
	// The ID of the order to delete.
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type DeleteSynchronizationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
