// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// GetSynchronizationExport200ApplicationJSON - OK
type GetSynchronizationExport200ApplicationJSON struct {
	Actions []string `json:"actions,omitempty"`
}

type GetSynchronizationExportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetSynchronizationExport200ApplicationJSONObject *GetSynchronizationExport200ApplicationJSON
}
