// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// GetSynchronizationImport200ApplicationJSON - OK
type GetSynchronizationImport200ApplicationJSON struct {
	Actions []string `json:"actions,omitempty"`
}

type GetSynchronizationImportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetSynchronizationImport200ApplicationJSONObject *GetSynchronizationImport200ApplicationJSON
}
