// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"snowmirror/internal/sdk/pkg/models/shared"
)

type GetSynchronizationRequest struct {
	// Id of the synchronization.
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type GetSynchronizationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Synchronization *shared.Synchronization
}
