// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"snowmirror/internal/sdk/pkg/models/shared"
)

type UpdateSynchronizationRequest struct {
	// A JSON representation of the Api to upsert
	CreateSynchronizationInput shared.CreateSynchronizationInput `request:"mediaType=application/json"`
	// The id of the sync.
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateSynchronizationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Synchronization *shared.Synchronization
}
